name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project

        uses: actions/checkout@v3
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
          
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3.2.0
      
      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-sonarscanner
          dotnet tool install dotnet-coverage
  
      - name: Analyze with Sonar Scanner
        run: |
          dotnet sonarscanner begin /k:MarkMenchavez_Referentials /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.host.url="https://sonarcloud.io" /o:markmenchavez
          dotnet build --no-incremental
          dotnet dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
